In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Getting tensor back as Python item
scalar.item()

7

In [5]:
# Creating the Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Creating the Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
T = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# Generating the Random Tensor
A = torch.rand(2,4,3,3)
A

tensor([[[[0.7711, 0.7567, 0.3260],
          [0.2938, 0.3323, 0.1046],
          [0.9215, 0.8533, 0.5011]],

         [[0.8347, 0.8757, 0.7542],
          [0.3341, 0.1841, 0.9177],
          [0.6653, 0.2851, 0.5909]],

         [[0.4632, 0.3497, 0.9749],
          [0.4630, 0.1533, 0.3243],
          [0.3691, 0.0826, 0.7249]],

         [[0.4842, 0.0459, 0.2865],
          [0.8675, 0.9563, 0.9361],
          [0.9921, 0.2593, 0.0227]]],


        [[[0.9891, 0.9062, 0.4047],
          [0.2630, 0.4265, 0.2154],
          [0.0773, 0.2189, 0.3651]],

         [[0.7196, 0.8435, 0.6798],
          [0.9260, 0.1579, 0.3651],
          [0.4283, 0.4292, 0.1639]],

         [[0.3744, 0.8749, 0.9873],
          [0.1871, 0.9177, 0.7194],
          [0.0674, 0.7760, 0.2367]],

         [[0.7361, 0.7932, 0.4973],
          [0.7502, 0.3762, 0.3625],
          [0.0976, 0.5667, 0.1591]]]])

In [18]:
A.ndim

4

In [19]:
A.shape

torch.Size([2, 4, 3, 3])

In [20]:
# Using arange function to generate Random Tensors
B = torch.arange(0,360,1).reshape(4, 3, 2, 5, 3)
print(B)
print(B.shape)

tensor([[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8],
           [  9,  10,  11],
           [ 12,  13,  14]],

          [[ 15,  16,  17],
           [ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26],
           [ 27,  28,  29]]],


         [[[ 30,  31,  32],
           [ 33,  34,  35],
           [ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53],
           [ 54,  55,  56],
           [ 57,  58,  59]]],


         [[[ 60,  61,  62],
           [ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71],
           [ 72,  73,  74]],

          [[ 75,  76,  77],
           [ 78,  79,  80],
           [ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]]]],



        [[[[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98],
           [ 99, 100, 101],
           [102, 103, 104]],

In [21]:
# Another way of Generating Tensor
C = torch.tensor(
    [[[[i + j + k + l for l in range(4)]
       for k in range(3)]
       for j in range(3)]
       for i in range(1)]
)

print(C)
print(C.shape)


tensor([[[[0, 1, 2, 3],
          [1, 2, 3, 4],
          [2, 3, 4, 5]],

         [[1, 2, 3, 4],
          [2, 3, 4, 5],
          [3, 4, 5, 6]],

         [[2, 3, 4, 5],
          [3, 4, 5, 6],
          [4, 5, 6, 7]]]])
torch.Size([1, 3, 3, 4])


## Creating Tensors with Zeroes and Ones

In [22]:
zeroes = torch.zeros(3, 3, 4)
zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
zeroes * C

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [24]:
ones = torch.ones(3, 3, 4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
print(ones.ndim)
print(ones.shape)
print(ones.dtype)

3
torch.Size([3, 3, 4])
torch.float32


## Creating Tensors like other Tensors

In [26]:
# It will create the same shape tensor like the given tensor, we can fill it up with ones or zeros.
CT = torch.ones_like(input=A)
CT

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [27]:
CT = torch.zeros_like(input=A)
CT

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

## Tensor Datatypes

In [28]:
fl_32_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = None)
fl_32_tensor

tensor([2., 4., 7.])

In [29]:
# Even after defining the Datatype as NONE, it will allot float32 by default
fl_32_tensor.dtype

torch.float32

In [30]:
fl_16_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = torch.float16, device=None, requires_grad=False)
fl_16_tensor

tensor([2., 4., 7.], dtype=torch.float16)

In [31]:
fl_16_tensor.dtype

torch.float16

In [32]:
# Changing the Datatype of float32 to float16
fl_32_tensor = fl_32_tensor.type(torch.float16)
fl_32_tensor

tensor([2., 4., 7.], dtype=torch.float16)

## Checking Tensor Device

In [33]:
fl_16_tensor.device

device(type='cpu')

## Tensor Operations

#### Addition

In [36]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 10

#### Subtraction

In [37]:
tensor - 10

tensor([1, 2, 3])

In [38]:
tensor.sub(10) # Built-in Function for Subtraction

tensor([1, 2, 3])

#### Multiplication

In [39]:
tensor * 10

tensor([110, 120, 130])

In [40]:
tensor.mul(10)

tensor([110, 120, 130])

#### Element-Wise Multiplication, Dot Product, Matrix Multiplication

In [41]:
tensor

tensor([11, 12, 13])

In [42]:
# Element - Wise Multiplication
tensor * tensor

tensor([121, 144, 169])

In [45]:
# Dot Product (It is always equal to the summation of Element-Wise Multiplication Matrix)
# So, in this case it is (121 + 144 + 169)
torch.dot(tensor, tensor)

tensor(434)

In [50]:
# matmul does dot product for 1D Vectors instead of Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(434)

In [49]:
# Matrix Multiplication
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix2 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix1.matmul(matrix2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])