In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Getting tensor back as Python item
scalar.item()

7

In [5]:
# Creating the Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Creating the Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
T = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# Generating the Random Tensor
A = torch.rand(2,4,3,3)
A

tensor([[[[0.2908, 0.0865, 0.0595],
          [0.4696, 0.9589, 0.2832],
          [0.2241, 0.7116, 0.6921]],

         [[0.0118, 0.8523, 0.6849],
          [0.3814, 0.9735, 0.6875],
          [0.1772, 0.1392, 0.3997]],

         [[0.2893, 0.7965, 0.6569],
          [0.5328, 0.8842, 0.8865],
          [0.4243, 0.5006, 0.6854]],

         [[0.9472, 0.7240, 0.1880],
          [0.6097, 0.2483, 0.2013],
          [0.2034, 0.3502, 0.1396]]],


        [[[0.0269, 0.9195, 0.4690],
          [0.4664, 0.8769, 0.1440],
          [0.5868, 0.0741, 0.2336]],

         [[0.2895, 0.1481, 0.2815],
          [0.1168, 0.0405, 0.9547],
          [0.6806, 0.8951, 0.8188]],

         [[0.7718, 0.6538, 0.2557],
          [0.9608, 0.9736, 0.7171],
          [0.1623, 0.3031, 0.9715]],

         [[0.1930, 0.9522, 0.0714],
          [0.1891, 0.6257, 0.4811],
          [0.0015, 0.5612, 0.5370]]]])

In [18]:
A.ndim

4

In [19]:
A.shape

torch.Size([2, 4, 3, 3])

In [20]:
# Using arange function to generate Random Tensors
B = torch.arange(0,360,1).reshape(4, 3, 2, 5, 3)
print(B)
print(B.shape)

tensor([[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8],
           [  9,  10,  11],
           [ 12,  13,  14]],

          [[ 15,  16,  17],
           [ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26],
           [ 27,  28,  29]]],


         [[[ 30,  31,  32],
           [ 33,  34,  35],
           [ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53],
           [ 54,  55,  56],
           [ 57,  58,  59]]],


         [[[ 60,  61,  62],
           [ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71],
           [ 72,  73,  74]],

          [[ 75,  76,  77],
           [ 78,  79,  80],
           [ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]]]],



        [[[[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98],
           [ 99, 100, 101],
           [102, 103, 104]],

In [21]:
# Another way of Generating Tensor
C = torch.tensor(
    [[[[i + j + k + l for l in range(4)]
       for k in range(3)]
       for j in range(3)]
       for i in range(1)]
)

print(C)
print(C.shape)


tensor([[[[0, 1, 2, 3],
          [1, 2, 3, 4],
          [2, 3, 4, 5]],

         [[1, 2, 3, 4],
          [2, 3, 4, 5],
          [3, 4, 5, 6]],

         [[2, 3, 4, 5],
          [3, 4, 5, 6],
          [4, 5, 6, 7]]]])
torch.Size([1, 3, 3, 4])


## Creating Tensors with Zeroes and Ones

In [22]:
zeroes = torch.zeros(3, 3, 4)
zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
zeroes * C

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [24]:
ones = torch.ones(3, 3, 4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
print(ones.ndim)
print(ones.shape)
print(ones.dtype)

3
torch.Size([3, 3, 4])
torch.float32


## Creating Tensors like other Tensors

In [26]:
# It will create the same shape tensor like the given tensor, we can fill it up with ones or zeros.
CT = torch.ones_like(input=A)
CT

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [27]:
CT = torch.zeros_like(input=A)
CT

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

## Tensor Datatypes

In [28]:
fl_32_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = None)
fl_32_tensor

tensor([2., 4., 7.])

In [29]:
# Even after defining the Datatype as NONE, it will allot float32 by default
fl_32_tensor.dtype

torch.float32

In [30]:
fl_16_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = torch.float16, device=None, requires_grad=False)
fl_16_tensor

tensor([2., 4., 7.], dtype=torch.float16)

In [31]:
fl_16_tensor.dtype

torch.float16

In [32]:
# Changing the Datatype of float32 to float16
fl_32_tensor = fl_32_tensor.type(torch.float16)
fl_32_tensor

tensor([2., 4., 7.], dtype=torch.float16)

## Checking Tensor Device

In [33]:
fl_16_tensor.device

device(type='cpu')

## Tensor Operations

#### Addition

In [34]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 10

#### Subtraction

In [35]:
tensor - 10

tensor([1, 2, 3])

In [36]:
tensor.sub(10) # Built-in Function for Subtraction

tensor([1, 2, 3])

#### Multiplication

In [37]:
tensor * 10

tensor([110, 120, 130])

In [38]:
tensor.mul(10)

tensor([110, 120, 130])

#### Element-Wise Multiplication, Dot Product, Matrix Multiplication

In [39]:
tensor

tensor([11, 12, 13])

In [40]:
# Element - Wise Multiplication
tensor * tensor

tensor([121, 144, 169])

In [41]:
# Dot Product (It is always equal to the summation of Element-Wise Multiplication Matrix)
# So, in this case it is (121 + 144 + 169)
torch.dot(tensor, tensor)

tensor(434)

In [42]:
# matmul does dot product for 1D Vectors instead of Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(434)

In [43]:
# Matrix Multiplication
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix2 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix1.matmul(matrix2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

### Tensor Aggregation (Min, Max, Mean, Sum, etc.)

In [44]:
x = torch.arange(0, 101, 4)
x

tensor([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [45]:
x.dtype

torch.int64

#### Minimum

In [46]:
torch.min(x)

tensor(0)

In [47]:
x.min()

tensor(0)

#### Maximum

In [48]:
torch.max(x)

tensor(100)

In [49]:
x.max()

tensor(100)

#### Mean

In [50]:
torch.mean(x.type(torch.float32)) # Changed the Datatype to float32 as torch.mean() requires float32 datatype

tensor(50.)

In [51]:
x.type(torch.float32).mean()

tensor(50.)

#### Sum

In [52]:
torch.sum(x)

tensor(1300)

In [53]:
x.sum()

tensor(1300)

### Index Position of Min and Max

In [54]:
# It returns the index value of minimum value in a tensor
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [55]:
# It returns the index value of maximum value in a tensor
torch.argmax(x), x.argmax()

(tensor(25), tensor(25))

### View and Stacking Tensors

#### View

In [56]:
x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [57]:
# Here z shares the same memory as of x, so changing z will change x as well
z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [58]:
z[:, 0] = 4
z, x

(tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

#### Stacking

In [72]:
x_stacked = torch.stack((x, x, x, x), dim = 0)
x_stacked

tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [73]:
x_stacked.shape

torch.Size([4, 10])

In [69]:
x_stacked = torch.vstack((x, x, x, x))
x_stacked

tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [66]:
# Creates a Dimension, and transposes the first tensor as first row etc.
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 4,  4,  4,  4],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [68]:
# It just concatenates horizontally, it is different from others.
x_stacked = torch.hstack((x, x, x, x))
x_stacked

tensor([ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  2,  3,  4,  5,  6,  7,  8,
         9, 10,  4,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  2,  3,  4,  5,  6,
         7,  8,  9, 10])

### Squeeze
The `squeeze()` function removes all dimensions of size 1 from a tensor.

In [80]:
# Create a tensor with a size of (1, 3, 1, 4)
tensor = torch.randn(1, 3, 1, 4)
print("Original tensor shape:", tensor.shape)

# Apply squeeze to remove all dimensions of size 1
squeezed_tensor = tensor.squeeze()
print("After squeeze:", squeezed_tensor.shape)

Original tensor shape: torch.Size([1, 3, 1, 4])
After squeeze: torch.Size([3, 4])


### Unsqueeze
The `unsqueeze()` function adds a singleton dimension (dimension of size 1) at a specific position in the tensor.

In [79]:
# Create a tensor with a size of (3, 4)
tensor = torch.randn(3, 4)
print("Original tensor shape:", tensor.shape)

# Apply unsqueeze to add a dimension at position 0
unsqueezed_tensor = tensor.unsqueeze(0)
print("After unsqueeze at 0:", unsqueezed_tensor.shape)

# Apply unsqueeze to add a dimension at position 2
unsqueezed_tensor_1 = tensor.unsqueeze(1)
print("After unsqueeze at 1:", unsqueezed_tensor_1.shape)

# Apply unsqueeze to add a dimension at position 2
unsqueezed_tensor_2 = tensor.unsqueeze(2)
print("After unsqueeze at 2:", unsqueezed_tensor_2.shape)

Original tensor shape: torch.Size([3, 4])
After unsqueeze at 0: torch.Size([1, 3, 4])
After unsqueeze at 1: torch.Size([3, 1, 4])
After unsqueeze at 2: torch.Size([3, 4, 1])


### Permute
In PyTorch, `permute()` is used to change the order of dimensions in a tensor. It allows you to rearrange the axes of the tensor to a new specified order.

In [86]:
tensor = torch.randn(2, 3, 4)
print("Original tensor shape:", tensor.shape)

# Applying permute to change the dimension order
permuted_tensor = tensor.permute(1, 0, 2)  # Swap 0th and 1st dimensions
print("Permuted tensor shape:", permuted_tensor.shape)

Original tensor shape: torch.Size([2, 3, 4])
Permuted tensor shape: torch.Size([3, 2, 4])
