In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Getting tensor back as Python item
scalar.item()

7

In [5]:
# Creating the Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Creating the Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
T = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# Generating the Random Tensor
A = torch.rand(2,4,3,3)
A

tensor([[[[0.0229, 0.6942, 0.4168],
          [0.7515, 0.4683, 0.3074],
          [0.3539, 0.2892, 0.2200]],

         [[0.4296, 0.5479, 0.0062],
          [0.0171, 0.3266, 0.7629],
          [0.1819, 0.1393, 0.5410]],

         [[0.6567, 0.7633, 0.8096],
          [0.6389, 0.2824, 0.2708],
          [0.6895, 0.8540, 0.4130]],

         [[0.9730, 0.5877, 0.1450],
          [0.7232, 0.9593, 0.3634],
          [0.1488, 0.1228, 0.4877]]],


        [[[0.9065, 0.7158, 0.4320],
          [0.7462, 0.0283, 0.4065],
          [0.5375, 0.8820, 0.5465]],

         [[0.5291, 0.8500, 0.6323],
          [0.9086, 0.1363, 0.6540],
          [0.8734, 0.2745, 0.9666]],

         [[0.2097, 0.0530, 0.0732],
          [0.6618, 0.4827, 0.1496],
          [0.9994, 0.2555, 0.3963]],

         [[0.2450, 0.2363, 0.2484],
          [0.8016, 0.0242, 0.5511],
          [0.3930, 0.1269, 0.6422]]]])

In [18]:
A.ndim

4

In [19]:
A.shape

torch.Size([2, 4, 3, 3])

In [20]:
# Using arange function to generate Random Tensors
B = torch.arange(0,360,1).reshape(4, 3, 2, 5, 3)
print(B)
print(B.shape)

tensor([[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8],
           [  9,  10,  11],
           [ 12,  13,  14]],

          [[ 15,  16,  17],
           [ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26],
           [ 27,  28,  29]]],


         [[[ 30,  31,  32],
           [ 33,  34,  35],
           [ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53],
           [ 54,  55,  56],
           [ 57,  58,  59]]],


         [[[ 60,  61,  62],
           [ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71],
           [ 72,  73,  74]],

          [[ 75,  76,  77],
           [ 78,  79,  80],
           [ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]]]],



        [[[[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98],
           [ 99, 100, 101],
           [102, 103, 104]],

In [21]:
# Another way of Generating Tensor
C = torch.tensor(
    [[[[i + j + k + l for l in range(4)]
       for k in range(3)]
       for j in range(3)]
       for i in range(2)]
)

print(C)
print(C.shape)


tensor([[[[0, 1, 2, 3],
          [1, 2, 3, 4],
          [2, 3, 4, 5]],

         [[1, 2, 3, 4],
          [2, 3, 4, 5],
          [3, 4, 5, 6]],

         [[2, 3, 4, 5],
          [3, 4, 5, 6],
          [4, 5, 6, 7]]],


        [[[1, 2, 3, 4],
          [2, 3, 4, 5],
          [3, 4, 5, 6]],

         [[2, 3, 4, 5],
          [3, 4, 5, 6],
          [4, 5, 6, 7]],

         [[3, 4, 5, 6],
          [4, 5, 6, 7],
          [5, 6, 7, 8]]]])
torch.Size([2, 3, 3, 4])
