In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Getting tensor back as Python item
scalar.item()

7

In [5]:
# Creating the Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Creating the Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
T = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
# Generating the Random Tensor
A = torch.rand(2,4,3,3)
A

tensor([[[[0.9477, 0.9960, 0.6090],
          [0.8050, 0.7896, 0.0627],
          [0.5048, 0.1254, 0.6732]],

         [[0.6942, 0.7906, 0.0625],
          [0.6337, 0.0090, 0.3814],
          [0.3131, 0.6457, 0.7087]],

         [[0.9788, 0.3452, 0.9262],
          [0.9076, 0.6426, 0.0621],
          [0.9345, 0.9792, 0.9536]],

         [[0.7652, 0.3324, 0.6622],
          [0.4776, 0.7970, 0.6278],
          [0.3802, 0.9535, 0.7630]]],


        [[[0.3770, 0.0466, 0.8549],
          [0.5815, 0.6799, 0.0668],
          [0.1403, 0.4532, 0.6303]],

         [[0.9378, 0.5534, 0.1581],
          [0.6415, 0.7400, 0.6141],
          [0.5991, 0.4136, 0.8161]],

         [[0.4277, 0.6672, 0.7045],
          [0.7548, 0.7327, 0.1253],
          [0.3487, 0.8647, 0.5465]],

         [[0.5401, 0.1619, 0.8832],
          [0.6939, 0.2736, 0.1811],
          [0.5722, 0.9315, 0.8921]]]])

In [18]:
A.ndim

4

In [19]:
A.shape

torch.Size([2, 4, 3, 3])

In [20]:
# Using arange function to generate Random Tensors
B = torch.arange(0,360,1).reshape(4, 3, 2, 5, 3)
print(B)
print(B.shape)

tensor([[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8],
           [  9,  10,  11],
           [ 12,  13,  14]],

          [[ 15,  16,  17],
           [ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26],
           [ 27,  28,  29]]],


         [[[ 30,  31,  32],
           [ 33,  34,  35],
           [ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53],
           [ 54,  55,  56],
           [ 57,  58,  59]]],


         [[[ 60,  61,  62],
           [ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71],
           [ 72,  73,  74]],

          [[ 75,  76,  77],
           [ 78,  79,  80],
           [ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]]]],



        [[[[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98],
           [ 99, 100, 101],
           [102, 103, 104]],

In [21]:
# Another way of Generating Tensor
C = torch.tensor(
    [[[[i + j + k + l for l in range(4)]
       for k in range(3)]
       for j in range(3)]
       for i in range(1)]
)

print(C)
print(C.shape)


tensor([[[[0, 1, 2, 3],
          [1, 2, 3, 4],
          [2, 3, 4, 5]],

         [[1, 2, 3, 4],
          [2, 3, 4, 5],
          [3, 4, 5, 6]],

         [[2, 3, 4, 5],
          [3, 4, 5, 6],
          [4, 5, 6, 7]]]])
torch.Size([1, 3, 3, 4])


## Creating Tensors with Zeroes and Ones

In [22]:
zeroes = torch.zeros(3, 3, 4)
zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
zeroes * C

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [24]:
ones = torch.ones(3, 3, 4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
print(ones.ndim)
print(ones.shape)
print(ones.dtype)

3
torch.Size([3, 3, 4])
torch.float32


## Creating Tensors like other Tensors

In [26]:
# It will create the same shape tensor like the given tensor, we can fill it up with ones or zeros.
CT = torch.ones_like(input=A)
CT

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [27]:
CT = torch.zeros_like(input=A)
CT

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

## Tensor Datatypes

In [28]:
fl_32_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = None)
fl_32_tensor

tensor([2., 4., 7.])

In [29]:
# Even after defining the Datatype as NONE, it will allot float32 by default
fl_32_tensor.dtype

torch.float32

In [30]:
fl_16_tensor = torch.tensor([2.0, 4.0, 7.0], dtype = torch.float16, device=None, requires_grad=False)
fl_16_tensor

tensor([2., 4., 7.], dtype=torch.float16)

In [31]:
fl_16_tensor.dtype

torch.float16

In [32]:
# Changing the Datatype of float32 to float16
fl_32_tensor = fl_32_tensor.type(torch.float16)
fl_32_tensor

tensor([2., 4., 7.], dtype=torch.float16)

## Checking Tensor Device

In [33]:
fl_16_tensor.device

device(type='cpu')

## Tensor Operations

#### Addition

In [34]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 10

#### Subtraction

In [35]:
tensor - 10

tensor([1, 2, 3])

In [36]:
tensor.sub(10) # Built-in Function for Subtraction

tensor([1, 2, 3])

#### Multiplication

In [37]:
tensor * 10

tensor([110, 120, 130])

In [38]:
tensor.mul(10)

tensor([110, 120, 130])

#### Element-Wise Multiplication, Dot Product, Matrix Multiplication

In [39]:
tensor

tensor([11, 12, 13])

In [40]:
# Element - Wise Multiplication
tensor * tensor

tensor([121, 144, 169])

In [41]:
# Dot Product (It is always equal to the summation of Element-Wise Multiplication Matrix)
# So, in this case it is (121 + 144 + 169)
torch.dot(tensor, tensor)

tensor(434)

In [42]:
# matmul does dot product for 1D Vectors instead of Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(434)

In [43]:
# Matrix Multiplication
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix2 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix1.matmul(matrix2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

### Tensor Aggregation (Min, Max, Mean, Sum, etc.)

In [44]:
x = torch.arange(0, 101, 4)
x

tensor([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [45]:
x.dtype

torch.int64

#### Minimum

In [46]:
torch.min(x)

tensor(0)

In [47]:
x.min()

tensor(0)

#### Maximum

In [48]:
torch.max(x)

tensor(100)

In [49]:
x.max()

tensor(100)

#### Mean

In [50]:
torch.mean(x.type(torch.float32)) # Changed the Datatype to float32 as torch.mean() requires float32 datatype

tensor(50.)

In [51]:
x.type(torch.float32).mean()

tensor(50.)

#### Sum

In [52]:
torch.sum(x)

tensor(1300)

In [53]:
x.sum()

tensor(1300)

### Index Position of Min and Max

In [54]:
# It returns the index value of minimum value in a tensor
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [55]:
# It returns the index value of maximum value in a tensor
torch.argmax(x), x.argmax()

(tensor(25), tensor(25))

### View and Stacking Tensors

#### View

In [56]:
x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [57]:
# Here z shares the same memory as of x, so changing z will change x as well
z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [58]:
z[:, 0] = 4
z, x

(tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

#### Stacking

In [59]:
x_stacked = torch.stack((x, x, x, x), dim = 0)
x_stacked

tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [60]:
x_stacked.shape

torch.Size([4, 10])

In [61]:
x_stacked = torch.vstack((x, x, x, x))
x_stacked

tensor([[ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [62]:
# Creates a Dimension, and transposes the first tensor as first row etc.
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 4,  4,  4,  4],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [63]:
# It just concatenates horizontally, it is different from others.
x_stacked = torch.hstack((x, x, x, x))
x_stacked

tensor([ 4,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  2,  3,  4,  5,  6,  7,  8,
         9, 10,  4,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  2,  3,  4,  5,  6,
         7,  8,  9, 10])

### Squeeze
The `squeeze()` function removes all dimensions of size 1 from a tensor.

In [64]:
# Create a tensor with a size of (1, 3, 1, 4)
tensor = torch.randn(1, 3, 1, 4)
print("Original tensor shape:", tensor.shape)

# Apply squeeze to remove all dimensions of size 1
squeezed_tensor = tensor.squeeze()
print("After squeeze:", squeezed_tensor.shape)

Original tensor shape: torch.Size([1, 3, 1, 4])
After squeeze: torch.Size([3, 4])


### Unsqueeze
The `unsqueeze()` function adds a singleton dimension (dimension of size 1) at a specific position in the tensor.

In [65]:
# Create a tensor with a size of (3, 4)
tensor = torch.randn(3, 4)
print("Original tensor shape:", tensor.shape)

# Apply unsqueeze to add a dimension at position 0
unsqueezed_tensor = tensor.unsqueeze(0)
print("After unsqueeze at 0:", unsqueezed_tensor.shape)

# Apply unsqueeze to add a dimension at position 1
unsqueezed_tensor_1 = tensor.unsqueeze(1)
print("After unsqueeze at 1:", unsqueezed_tensor_1.shape)

# Apply unsqueeze to add a dimension at position 2
unsqueezed_tensor_2 = tensor.unsqueeze(2)
print("After unsqueeze at 2:", unsqueezed_tensor_2.shape)

Original tensor shape: torch.Size([3, 4])
After unsqueeze at 0: torch.Size([1, 3, 4])
After unsqueeze at 1: torch.Size([3, 1, 4])
After unsqueeze at 2: torch.Size([3, 4, 1])


### Permute
In PyTorch, `permute()` is used to change the order of dimensions in a tensor. It allows you to rearrange the axes of the tensor to a new specified order.

In [66]:
tensor = torch.randn(2, 3, 4)
print("Original tensor shape:", tensor.shape)

# Applying permute to change the dimension order
permuted_tensor = tensor.permute(1, 0, 2)  # Swap 0th and 1st dimensions
print("Permuted tensor shape:", permuted_tensor.shape)

Original tensor shape: torch.Size([2, 3, 4])
Permuted tensor shape: torch.Size([3, 2, 4])


## Indexing

In [67]:
x = torch.arange(0, 18).reshape(2, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [68]:
x[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [69]:
x[1,1,1]

tensor(13)

In [70]:
x[0,1]

tensor([3, 4, 5])

In [71]:
x[0,2,:2]

tensor([6, 7])

In [72]:
x[0,2,0:1]

tensor([6])

In [73]:
x[0,:,-1]

tensor([2, 5, 8])

In [74]:
x[1,1:,1]

tensor([13, 16])

## Tensors and NumPy

### NumPy to Tensor

In [75]:
import numpy as np

a = np.arange(1,11)
tensor = torch.from_numpy(a)
a, tensor, tensor.dtype

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.int64)

In [76]:
a = a + 1
a, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

### Tensor to NumPy

In [77]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Seed)

In [78]:
# We need to call Random Seed everytime before creating tensor if we want the reproducibility.
random_seed = 42

torch.manual_seed(random_seed)
random1 = torch.rand(7,7)

torch.manual_seed(random_seed)
random2 = torch.rand(7,7)

print(random1)
print("\n", random2)
print("\n", random1 == random2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

 tensor([[True, True, True, True, True, True, True],
        [True, Tru

## CUDA, GPU & CPU

In [79]:
torch.cuda.is_available()

False

In [80]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [81]:
torch.cuda.device_count()

0

In [82]:
tensor1 = torch.tensor([1,2,3])
tensor1.device

device(type='cpu')

### **Note -**

* Remember, when converting tensor back to numpy, don't forget to change the device to cpu first as numpy array requires cpu not gpu.